name: Video Uploader
on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'Direct Link to Video'
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Download Video
        run: |
          wget --user-agent="Mozilla/5.0" --continue --output-document=input_movie.mp4 "${{ github.event.inputs.video_url }}"
        
      - name: Optimize for Streaming
        run: |
          ffmpeg -i input_movie.mp4 -c copy -map 0 -movflags +faststart movie.mp4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: movie-${{ github.run_number }}
          files: movie.mp4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
