name: Seedr to Permanent Link
on:
  workflow_dispatch:
    inputs:
      seedr_link:
        description: 'لینکی دایرێکتی سێدر لێرە دابنێ'
        required: true

jobs:
  transfer:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download from Seedr
        run: |
          # گیتھەب لێرەدا فایلەکە بە خێراییەکی خەیاڵی لە سێدرەوە ڕادەکێشێت
          curl -L "${{ github.event.inputs.seedr_link }}" -o movie.mp4

      - name: Create Permanent Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v-direct-${{ github.run_number }}"
          files: movie.mp4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
