name: Video Direct Linker
on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'Direct Link to Video'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Video
        run: |
          wget --user-agent="Mozilla/5.0" "${{ github.event.inputs.video_url }}" -O movie.mp4

      - name: Manual Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add movie.mp4
          git commit -m "Update Video"
          git push --force origin main
